#!/bin/bash

# Si se le pasa un argumento, es que el usuario seleccionó un archivo
if [ "$@" ]; then
    # Abrimos el archivo en segundo plano y cerramos Rofi
    nohup xdg-open "$@" >/dev/null 2>&1 &
    exit
else
    # Si no hay argumento, fdfind escupe la lista completa de archivos
    # He limitado a $HOME, pero puedes añadir carpetas de tus proyectos
    fdfind . $HOME --type f --exclude .git --exclude node_modules --exclude .cache
fi
